services:
  dev:
    tty: true
    build: 
      context: ./dev
      additional_contexts: 
        - basefolder=${USER_BASE_FOLDER}
      args:
        - REQUIREMENTS=${PYTHON_PIP_REQUIREMENTS}
        - USER_BASE_FOLDER=${USER_BASE_FOLDER}
    
    container_name: ${COMPOSE_PROJECT_NAME}_dev
    volumes:
      - ${USER_BASE_FOLDER}:/home/
    networks:
      - network
    restart: unless-stopped

  postgresql:
    build: ./postgresql
    container_name: ${COMPOSE_PROJECT_NAME}_postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${POSTGRESQL_EXPOSED_PORT}:5432
    volumes:
      - sw_development_config_postgresql:/var/lib/postgresql/data
      - ${USER_BASE_FOLDER}:/home/
    networks:
      - network
    restart: unless-stopped

  pgadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    image: dpage/pgadmin4:latest
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - sw_development_config_pgadmin:/var/lib/pgadmin # to choose your personal directory, change only the left path.
       - ${USER_BASE_FOLDER}:/home/
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"  
    networks:
      - network
    restart: unless-stopped

volumes:
  sw_development_config_postgresql:
  sw_development_config_pgadmin:

networks:
  network: 
    driver: bridge
