version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: sql
      MYSQL_PASSWORD: sql
    ports: "3306:3306"
    
  app:
    image: your_app_image # Sostituisci con l'immagine della tua applicazione
    restart: always
    depends_on: db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: database
    ports:
        "8000:8000" # Modifica la porta in base alla tua applicazione

